os: linux
dist: bionic

language: cpp
compiler:
 - clang
 - gcc

addons:
 apt:
  packages:
   - cmake
   - doxygen

script:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt update
 - sudo apt install gcc-9
 - sudo apt install g++-9
 - echo Check versions of compilers etc... #------------------------------------
 - sudo ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
 - sudo ln -s /usr/bin/g++-9 /usr/local/bin/g++
 - gcc -v
 - g++ -v
 - cmake --version
 - echo Create project directory... #------------------------------------
 - mkdir cmake-build
 - cd cmake-build
 - echo Create Project... #------------------------------------
 - cmake -DCMAKE_RULE_MESSAGES:BOOL=OFF -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..
 - echo Build Project... #------------------------------------
 - cmake --build .
 - ls -la
 - cd ..
# - doxygen Doxyfile

#deploy:
#    provider: pages
#    skip_cleanup: true
#    token: $GH_REPO_TOKEN
#    keep_history: true
#    local_dir: html
#    target_branch: gh-pages
#    on :
#        branch: master
#