# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
# - task: Bash@0
#   - inputs:
#     condition: neq( variables['Agent.OS'], 'Windows_NT')
#     targetType: 'inline'
#     script: |
#      echo Running install script on unix systems...
#      cd ./script/
#      ./unix-install.sh
 - task: PowerShell@0
   condition: eq( variables['Agent.OS'], 'Windows_NT' )
   inputs:
    targetType: 'inline'
    script: |
     Write-Host "Running install script on windows systems..."
     cd ./script/
     ./win-install.ps1
 - task: Bash@3
   inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'